RDEPENDS:${PN}:append:ibm-ac-server = " avsbus-control"
RDEPENDS:${PN}:append:witherspoon = " vrm-control"
RDEPENDS:${PN}:append:ibm-ac-server = " power-workarounds"
RDEPENDS:${PN}:remove:ibm-ac-server = " p9-vcs-workaround"
RDEPENDS:${PN}:remove:p10bmc = " p9-vcs-workaround"
