EKB_BRANCH = "main-p10"
EKB_URI = "git://git@github.com/open-power/pub-ekb;branch=${EKB_BRANCH}"
EKB_REV = "52e5c0038a50cc641dffdc6158f8c21930c70678"

REQ_ATTRS_XMLS = "chips/p10/procedures/xml/attribute_info/p10_clock_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_freq_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_ipl_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_nest_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_pervasive_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_runn_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_bars_attributes.xml \
           hwpf/fapi2/xml/attribute_info/unit_attributes.xml \
           hwpf/fapi2/xml/attribute_info/common_attributes.xml \
           hwpf/fapi2/xml/attribute_info/chip_attributes.xml"
